version: "3.9"

services:
  orchestration-api: &orchestration
    build:
      context: ./backend
      args:
        - "USERID=${USERID:-1000}"
        - "GROUPID=${GROUPID:-1000}"
        - "USERNAME=${USERNAME:-orcapp}"
    command: /app/sh/start.sh
    user: "1000:1000"
    env_file:
      - .env-app
    networks:
      - default
      - orchestration-network
    volumes:
      - ./pipelines:/pipelines # pipelines repo
      - ./pipelines/training_set_maker/data-example:/datasets # datasets repo
      - ./processes:/processes
      - ../archive/data:/archive/data # access to PZ server uploads
      - ./logs:/logs
      - ./db:/db
    depends_on:
      - rabbitmq

  orchestration-local-worker: &celery_local_worker
    <<: *orchestration
    hostname: "orchestration-local-worker"
    command: /app/sh/local_worker.sh
    depends_on:
      - orchestration-api

  rabbitmq:
    image: "rabbitmq:3.12.12-management"
    hostname: "rabbitmq"
    env_file:
      - .env-app
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
      - orchestration-network
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq/data/:/var/lib/rabbitmq/"
      - "./rabbitmq/log/:/var/log/rabbitmq/"

  orchestrator:
    image: nginx:1.21.6-alpine
    ports:
      - 8088:80
    volumes:
      - ./nginx.app.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - orchestration-network
    depends_on:
      - orchestration-api
      - rabbitmq

networks:
  orchestration-network:
    external: true
    driver: bridge
